### ISSUE TITLE
Research: Are RAM expansions working as expected?

### ISSUE THREAD

**Issue by sy2002** [MJoergen/VIC20MEGA65#1]
As you can see in the video, I am adding more and more RAM and VIC20 BASIC is recognizing it. But there are quite some combinations that are not recognized. No idea why:

* Bug in your code?
* Quirk in VIC20 BASIC?
* "Illegal combination?" of RAM Extensions

You might want to research a bit when you find time is ripe, like googling for VIC20 RAM TEST programs or reading about it. And just in case there are "illegal combinations": You might use the m2m-rom.asm callback function "OSM_SEL_PRE" and the functions from M2M/rom/tools.asm to prevent the user from choosing illegal combinations.

https://github.com/MJoergen/VIC20MEGA65/assets/6825267/5607d821-c5af-4812-9d51-a1ff5608eee9

**Comment by MJoergen** [comment]
I've used this [RAM test](https://github.com/svenpetersen1965/VIC-20-RAM-Expansion-Test-Software) and checked all 32 (!) combinations. They all work.

However, I do notice that not all combinations are recognized by the BASIC interpreter. But I think this is not a bug.

**Comment by sy2002** [comment]
@MJoergen Sounds great! Thank you! Closing this issue.
